---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}{% if kibana_full_version is defined and kibana_full_version != ''  %}-{{ kibana_full_version }}{% endif %}"
    state: "{{ kibana_package_state }}"
  register: kibana_install

- name: include kibana-plugins.yml
  include: kibana-plugins.yml
  when: kibana_plugins is defined or kibana_plugins_reinstall
  tags:
      - plugins

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
